# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Fernanda Reis Ribeiro
tagline:          'blog'
description:      'My Research Blog.'
url:              http://freisribeiro.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Ian Brunelli
  url:            https://google.com/+IanCamporezBrunelli

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover2.jpg

social:
  - icon:         twitter
    url:          
    desc:         Follow me on twitter

  - icon:         github
    url:          
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          
    desc:         Add me on google+

  - icon:         feed
    url:          http://camporez.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

  - title:        Portfolio
    url:          /portfolio

 - title:        Contact
    url:          /contact

copyright:
  author:         Camporez
  url:            http://camporez.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
